### PR TITLE
Added ESLint to reveal potential issues

### PR DESCRIPTION
**Pull request by ltsSmitty**
This branch adds a linter to the project. It will look like it's adding lots of errors, but it's trying to be helpful. Not sure how to be more clear about it, so [here's an article about why linters](https://blog.cloudanalogy.com/how-to-improve-your-javascript-code-quality-with-eslint/). 

If you decide to accept this, I can do some preliminary passes through the code to do some cleanup for you (mostly changing var to let/const or adding some stronger typing

### CODE REVIEW

**Comment by Die4Ever** [comment]
seems good to me, definitely something we needed

**Comment by Die4Ever** [comment]
I'm wondering if the `.ts` files should be separate pull requests, this has merge conflicts

maybe we should be doing a pull request for the `.ts` files before changing the config to actually enable these checks, that way it can be a smoother process

**Comment by Die4Ever** [comment]
also maybe we should start smaller, like

```
        "noImplicitAny": false,
        "noImplicitOverride": false,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": false,
        "strict": false,
```

gives only 26 errors instead of 207 errors

**Comment by Die4Ever** [comment]
I did make a branch with just your config changes, but this should probably only be merged after the `.ts` files are cleaned up

https://github.com/Crazycolbster/rollercoaster-tycoon-randomizer/compare/General_Killmore...Die4Ever:rollercoaster-tycoon-randomizer:linter-standalone

**Comment by ltsSmitty** [comment]
I like starting smaller as well. I tried it with some beefier rules and got bogged down for hours trying to sift through things.

**Pull request merged**
